name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
        
      - name: setup-go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v2.2.0
        with:
          go-version: '1.17'
       
      - name: Run tests for builder
        run: |
          set -euo pipefail
          
          # Download dependencies.
          go mod vendor
          # Build.
          go build -mod=vendor
          # Test.
          go test -mod=vendor -v ./...
